import test from 'node:test';
import assert from 'node:assert/strict';
import { cleanupExpiredPendingBookings, createDatabase } from './database.mjs';
import { TERMS_VERSION, confirmDemoPayment, createBlockedPeriod, createHold, createManualBooking, listAvailableSlots, listBookableDates, listBookingsRange, listNotifications, markBookingPaid, rescheduleBooking } from './booking-service.mjs';

const now=new Date('2026-06-10T06:00:00.000Z');
test('fixed weekday slots are returned per service',()=>{const db=createDatabase(':memory:');assert.deepEqual(listAvailableSlots(db,'balayage','2026-06-10',now),['10:00','14:00']);assert.deepEqual(listAvailableSlots(db,'cut','2026-06-10',now),['11:30','15:30']);});
test('fixed saturday slots include shortened second balayage window',()=>{const db=createDatabase(':memory:');assert.deepEqual(listAvailableSlots(db,'balayage','2026-06-13',now),['09:30','13:30']);const hold=createHold(db,{serviceId:'balayage',date:'2026-06-13',time:'13:30'},now);assert.equal(hold.endsAt.slice(11,16),'17:00');});
test('exactly six chronological days with at least one free slot are returned',()=>{const db=createDatabase(':memory:');createHold(db,{serviceId:'cut',date:'2026-06-10',time:'11:30'},now);createHold(db,{serviceId:'cut',date:'2026-06-10',time:'15:30'},now);const dates=listBookableDates(db,{serviceId:'cut',from:now});assert.equal(dates.length,6);assert.equal(dates.includes('2026-06-10'),false);assert.deepEqual(dates,[...dates].sort());});
test('same slot cannot be held twice',()=>{const db=createDatabase(':memory:');createHold(db,{serviceId:'cut',date:'2026-06-10',time:'11:30'},now);assert.throws(()=>createHold(db,{serviceId:'cut',date:'2026-06-10',time:'11:30'},now),/nicht mehr verfügbar/);});
test('expired hold is available again',()=>{const db=createDatabase(':memory:');createHold(db,{serviceId:'cut',date:'2026-06-10',time:'11:30'},now);assert.ok(listAvailableSlots(db,'cut','2026-06-10',new Date(now.getTime()+11*60_000)).includes('11:30'));});
test('demo payment creates booking',()=>{const db=createDatabase(':memory:');const hold=createHold(db,{serviceId:'cut',date:'2026-06-10',time:'11:30'},now);const booking=confirmDemoPayment(db,{holdId:hold.id,acceptedTermsVersion:TERMS_VERSION,customer:{firstName:'Anna',lastName:'Sommer',email:'anna@example.de',phone:'+491234',note:''}},new Date(now.getTime()+60_000));assert.equal(booking.depositCents,3000);assert.equal(listAvailableSlots(db,'cut','2026-06-10',now).includes('11:30'),false);});
test('manual booking appears in calendar without deposit',()=>{const db=createDatabase(':memory:');createManualBooking(db,{serviceId:'gloss',date:'2026-06-11',time:'11:30',customer:{firstName:'Mira',lastName:'Test'}},now);const items=listBookingsRange(db,'2026-06-09','2026-06-15');assert.equal(items.length,1);assert.equal(items[0].paymentStatus,'manual');assert.equal(items[0].depositCents,0);});
test('a free day removes all public availability',()=>{const db=createDatabase(':memory:');createBlockedPeriod(db,{date:'2026-06-12',reason:'Urlaub'});assert.deepEqual(listAvailableSlots(db,'cut','2026-06-12',now),[]);});
test('online confirmation creates an unread notification',()=>{const db=createDatabase(':memory:');const hold=createHold(db,{serviceId:'cut',date:'2026-06-10',time:'11:30'},now);confirmDemoPayment(db,{holdId:hold.id,acceptedTermsVersion:TERMS_VERSION,customer:{firstName:'Anna',lastName:'Sommer',email:'anna@example.de',phone:'+491234'}},new Date(now.getTime()+60_000));const notifications=listNotifications(db);assert.equal(notifications.length,1);assert.equal(notifications[0].readAt,null);});
test('admin can confirm the deposit manually',()=>{const db=createDatabase(':memory:');const hold=createHold(db,{serviceId:'cut',date:'2026-06-10',time:'11:30'},now);const booking=confirmDemoPayment(db,{holdId:hold.id,acceptedTermsVersion:TERMS_VERSION,customer:{firstName:'Anna',lastName:'Sommer',email:'anna@example.de',phone:'+491234'}},now);markBookingPaid(db,booking.id,new Date(now.getTime()+60_000));assert.equal(db.prepare('SELECT payment_status FROM bookings').get().payment_status,'paid');});
test('unpaid booking is auto-cancelled after two hours',()=>{const db=createDatabase(':memory:');const hold=createHold(db,{serviceId:'cut',date:'2026-06-10',time:'11:30'},now);confirmDemoPayment(db,{holdId:hold.id,acceptedTermsVersion:TERMS_VERSION,customer:{firstName:'Anna',lastName:'Sommer',email:'anna@example.de',phone:'+491234'}},now);cleanupExpiredPendingBookings(db,new Date(now.getTime()+2*60*60_000+1_000));assert.equal(db.prepare('SELECT status FROM bookings').get().status,'cancelled');assert.equal(listAvailableSlots(db,'cut','2026-06-10',new Date(now.getTime()+2*60*60_000+1_000)).includes('11:30'),true);assert.equal(listBookingsRange(db,'2026-06-10','2026-06-10').length,0);});
test('an existing booking can be moved to a free slot',()=>{const db=createDatabase(':memory:');const created=createManualBooking(db,{serviceId:'cut',date:'2026-06-10',time:'11:30',customer:{firstName:'Mira',lastName:'Test'}},now);rescheduleBooking(db,created.id,{date:'2026-06-11',time:'15:30'},now);const items=listBookingsRange(db,'2026-06-10','2026-06-11');assert.equal(items.length,1);assert.equal(items[0].startsAt.slice(0,16),'2026-06-11T15:30');});
