create extension if not exists pgcrypto;

create table if not exists public.services (
  id text primary key,
  name text not null,
  short_name text not null,
  duration_minutes integer not null check (duration_minutes > 0),
  active boolean not null default true
);

create table if not exists public.blocked_periods (
  id bigint generated by default as identity primary key,
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  reason text not null default 'Frei',
  created_at timestamptz not null default now(),
  check (ends_at > starts_at)
);

create table if not exists public.holds (
  id uuid primary key default gen_random_uuid(),
  service_id text not null references public.services(id),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  expires_at timestamptz not null,
  status text not null default 'active' check (status in ('active','released','converted','expired')),
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id uuid primary key default gen_random_uuid(),
  hold_id uuid unique references public.holds(id),
  service_id text not null references public.services(id),
  starts_at timestamptz not null,
  ends_at timestamptz not null,
  first_name text not null,
  last_name text not null,
  email text not null,
  phone text not null,
  note text,
  status text not null default 'confirmed' check (status in ('confirmed','cancelled')),
  deposit_cents integer not null default 3000,
  payment_status text not null default 'pending' check (payment_status in ('pending','paid','manual')),
  terms_version text not null,
  terms_accepted_at timestamptz not null,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  booking_id uuid references public.bookings(id),
  title text not null,
  message text not null,
  read_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists holds_time_idx on public.holds(starts_at, ends_at, status, expires_at);
create index if not exists bookings_time_idx on public.bookings(starts_at, ends_at, status);
create index if not exists blocks_time_idx on public.blocked_periods(starts_at, ends_at);

insert into public.services(id,name,short_name,duration_minutes) values
  ('balayage','Balayage inkl. Pflege, Schnitt und Styling','Balayage Komplett',240),
  ('cut','Schneiden','Schneiden',60),
  ('gloss','Glossing','Glossing',60),
  ('gloss-cut','Glossing & Schnitt','Glossing & Schnitt',60),
  ('colour','Colouring','Colouring',60)
on conflict (id) do update set name=excluded.name,short_name=excluded.short_name,duration_minutes=excluded.duration_minutes,active=true;

alter table public.services enable row level security;
alter table public.blocked_periods enable row level security;
alter table public.holds enable row level security;
alter table public.bookings enable row level security;
alter table public.notifications enable row level security;
alter table public.admin_users enable row level security;

revoke all on all tables in schema public from anon, authenticated;
grant select on public.services to anon, authenticated;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.admin_users where user_id=auth.uid()) $$;

create or replace function public.slot_candidates(p_service_id text,p_date date)
returns table(starts_at timestamptz,ends_at timestamptz,time_label text)
language plpgsql stable security definer set search_path=public
as $$
declare d integer:=extract(isodow from p_date); zone text:='Europe/Berlin';
begin
  if d=7 then return; end if;
  if p_service_id='balayage' then
    if d=6 then
      return query values
        ((p_date+time '09:30') at time zone zone,(p_date+time '13:30') at time zone zone,'09:30'),
        ((p_date+time '13:30') at time zone zone,(p_date+time '17:00') at time zone zone,'13:30');
    else
      return query values
        ((p_date+time '10:00') at time zone zone,(p_date+time '14:00') at time zone zone,'10:00'),
        ((p_date+time '14:00') at time zone zone,(p_date+time '18:00') at time zone zone,'14:00');
    end if;
  elsif exists(select 1 from public.services where id=p_service_id and active) then
    if d=6 then
      return query values
        ((p_date+time '10:45') at time zone zone,(p_date+time '11:45') at time zone zone,'10:45'),
        ((p_date+time '14:45') at time zone zone,(p_date+time '15:45') at time zone zone,'14:45');
    else
      return query values
        ((p_date+time '11:30') at time zone zone,(p_date+time '12:30') at time zone zone,'11:30'),
        ((p_date+time '15:30') at time zone zone,(p_date+time '16:30') at time zone zone,'15:30');
    end if;
  end if;
end $$;

create or replace function public.get_available_slots(p_service_id text,p_date date)
returns table(slot_time text)
language sql stable security definer set search_path=public
as $$
  select c.time_label from public.slot_candidates(p_service_id,p_date)c
  where c.starts_at>now()
    and not exists(select 1 from public.bookings b where b.status='confirmed' and b.starts_at<c.ends_at and b.ends_at>c.starts_at)
    and not exists(select 1 from public.holds h where h.status='active' and h.expires_at>now() and h.starts_at<c.ends_at and h.ends_at>c.starts_at)
    and not exists(select 1 from public.blocked_periods x where x.starts_at<c.ends_at and x.ends_at>c.starts_at)
  order by c.starts_at
$$;

create or replace function public.get_bookable_dates(p_service_id text)
returns table(date text)
language sql stable security definer set search_path=public
as $$
  select d::text from generate_series(current_date,current_date+interval '90 days',interval '1 day')g(d)
  where exists(select 1 from public.get_available_slots(p_service_id,d::date))
  order by d limit 6
$$;

create or replace function public.create_hold(p_service_id text,p_date date,p_time text)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare c record; result public.holds;
begin
  perform pg_advisory_xact_lock(hashtext(p_service_id||p_date::text||p_time));
  select * into c from public.slot_candidates(p_service_id,p_date) where time_label=p_time;
  if c is null or not exists(select 1 from public.get_available_slots(p_service_id,p_date) where slot_time=p_time) then
    raise exception 'Dieser Termin ist nicht mehr verfügbar.';
  end if;
  insert into public.holds(service_id,starts_at,ends_at,expires_at) values(p_service_id,c.starts_at,c.ends_at,now()+interval '10 minutes') returning * into result;
  return jsonb_build_object('id',result.id,'expiresAt',result.expires_at,'startsAt',result.starts_at,'endsAt',result.ends_at);
end $$;

create or replace function public.release_hold(p_hold_id uuid)
returns void language sql security definer set search_path=public
as $$ update public.holds set status='released' where id=p_hold_id and status='active' $$;

create or replace function public.confirm_booking(p_hold_id uuid,p_first_name text,p_last_name text,p_email text,p_phone text,p_note text,p_terms_version text)
returns jsonb language plpgsql security definer set search_path=public
as $$
declare h public.holds; b public.bookings;
begin
  if trim(coalesce(p_first_name,''))='' or trim(coalesce(p_last_name,''))='' or trim(coalesce(p_email,''))='' or trim(coalesce(p_phone,''))='' then
    raise exception 'Bitte alle Kontaktdaten vollständig ausfüllen.';
  end if;
  select * into h from public.holds where id=p_hold_id for update;
  if h is null or h.status<>'active' or h.expires_at<=now() then raise exception 'Die Reservierungszeit ist abgelaufen.'; end if;
  if exists(select 1 from public.bookings x where x.status='confirmed' and x.starts_at<h.ends_at and x.ends_at>h.starts_at) then raise exception 'Dieser Termin ist nicht mehr verfügbar.'; end if;
  insert into public.bookings(hold_id,service_id,starts_at,ends_at,first_name,last_name,email,phone,note,deposit_cents,payment_status,terms_version,terms_accepted_at)
  values(h.id,h.service_id,h.starts_at,h.ends_at,trim(p_first_name),trim(p_last_name),lower(trim(p_email)),trim(p_phone),nullif(trim(coalesce(p_note,'')),''),3000,'pending',p_terms_version,now()) returning * into b;
  update public.holds set status='converted' where id=h.id;
  insert into public.notifications(booking_id,title,message) values(b.id,'Neue Online-Buchung',b.first_name||' '||b.last_name||' hat einen Termin gebucht. Anzahlung noch offen.');
  return jsonb_build_object('id',b.id,'startsAt',b.starts_at,'depositCents',b.deposit_cents,'paymentStatus',b.payment_status);
end $$;

create or replace function public.admin_calendar(p_from date,p_to date)
returns table(id uuid,service_id text,service_name text,service_short text,duration integer,starts_at timestamptz,ends_at timestamptz,first_name text,last_name text,email text,phone text,note text,payment_status text,deposit_cents integer)
language plpgsql security definer set search_path=public
as $$ begin
  if not public.is_admin() then raise exception 'Nicht autorisiert.'; end if;
  return query select b.id,b.service_id,s.name,s.short_name,s.duration_minutes,b.starts_at,b.ends_at,b.first_name,b.last_name,b.email,b.phone,b.note,b.payment_status,b.deposit_cents
  from public.bookings b join public.services s on s.id=b.service_id where b.status='confirmed' and b.starts_at<((p_to+1)::timestamp at time zone 'Europe/Berlin') and b.ends_at>(p_from::timestamp at time zone 'Europe/Berlin') order by b.starts_at;
end $$;

create or replace function public.admin_blocks(p_from date,p_to date)
returns setof public.blocked_periods language plpgsql security definer set search_path=public
as $$ begin if not public.is_admin() then raise exception 'Nicht autorisiert.'; end if; return query select * from public.blocked_periods where starts_at<((p_to+1)::timestamp at time zone 'Europe/Berlin') and ends_at>(p_from::timestamp at time zone 'Europe/Berlin') order by starts_at; end $$;

create or replace function public.admin_notifications()
returns setof public.notifications language plpgsql security definer set search_path=public
as $$ begin if not public.is_admin() then raise exception 'Nicht autorisiert.'; end if; return query select * from public.notifications order by created_at desc limit 30; end $$;

create or replace function public.admin_mark_notifications_read()
returns void language plpgsql security definer set search_path=public
as $$ begin if not public.is_admin() then raise exception 'Nicht autorisiert.'; end if; update public.notifications set read_at=now() where read_at is null; end $$;

create or replace function public.admin_create_block(p_date date,p_reason text)
returns bigint language plpgsql security definer set search_path=public
as $$ declare result bigint; begin if not public.is_admin() then raise exception 'Nicht autorisiert.'; end if; insert into public.blocked_periods(starts_at,ends_at,reason) values(p_date::timestamp at time zone 'Europe/Berlin',(p_date+1)::timestamp at time zone 'Europe/Berlin',coalesce(nullif(trim(p_reason),''),'Frei')) returning id into result; return result; end $$;

create or replace function public.admin_delete_block(p_id bigint)
returns void language plpgsql security definer set search_path=public
as $$ begin if not public.is_admin() then raise exception 'Nicht autorisiert.'; end if; delete from public.blocked_periods where id=p_id; end $$;

create or replace function public.admin_cancel_booking(p_id uuid)
returns void language plpgsql security definer set search_path=public
as $$ begin if not public.is_admin() then raise exception 'Nicht autorisiert.'; end if; update public.bookings set status='cancelled' where id=p_id; end $$;

grant execute on function public.get_available_slots(text,date),public.get_bookable_dates(text),public.create_hold(text,date,text),public.release_hold(uuid),public.confirm_booking(uuid,text,text,text,text,text,text) to anon,authenticated;
grant execute on function public.is_admin(),public.admin_calendar(date,date),public.admin_blocks(date,date),public.admin_notifications(),public.admin_mark_notifications_read(),public.admin_create_block(date,text),public.admin_delete_block(bigint),public.admin_cancel_booking(uuid) to authenticated;
